// Generated by ChatGPT
module jk (
    input clk,    // Clock signal
    input reset,  // Active-high reset
    input j,      // J input
    input k,      // K input
    output reg q, // Output Q
    output q_bar  // Output Q-bar (inverse)
);

    // Continuous assignment for the inverse output
    assign q_bar = ~q;

    // Sequential logic triggered on the rising edge of the clock
    always @(posedge clk) begin
        if (reset) begin
            q <= 1'b0; // Reset state
        end else begin
            case ({j, k})
                2'b00 : q <= q;    // No change (Hold)
                2'b01 : q <= 1'b0; // Reset (Clear)
                2'b10 : q <= 1'b1; // Set
                2'b11 : q <= ~q;   // Toggle
            endcase
        end
    end

endmodule

